### ISSUE TITLE
[Bug] File picker not uploading files

### ISSUE THREAD

**Issue by korboybeats** [ssense1337/enmity-plugins#1]
The file picker plugin won't work for me. It just says "queued" and never uploads the file.

![32A19747-461C-40A4-941B-78D36BA59A67](https://user-images.githubusercontent.com/80824905/199888523-5fcc1716-8de0-4f02-8653-7c976e3f76a1.jpeg)

Device: M1 iPad Pro
Enmity version: 2.1.4
Discord version: 151.0

**Comment by ssense1337** [comment]
Fixed in latest update
